# Generated by Django 3.1.3 on 2020-12-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='country_iso',
            field=models.CharField(default='JOR', max_length=3, verbose_name='ISO Code'),
            preserve_default=False,
        ),
    ]
