# Generated by Django 2.1.7 on 2020-10-27 00:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(blank=True, max_length=255, null=True)),
                ('disease_alternative_names', models.CharField(blank=True, max_length=255, null=True)),
                ('disease_attack_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('disease_hospitalisation_cases', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('hospitalisation_length_stay', models.IntegerField(blank=True, null=True)),
                ('peak_attack_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('medicine_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_code', models.CharField(max_length=50)),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('frequency', models.IntegerField()),
                ('disease_medicine', models.ManyToManyField(to='calc.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('disease_6m_5yr', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('disease_6m_15yr', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calc.Scenario'),
        ),
    ]
