# Generated by Django 2.1.7 on 2020-10-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='incidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevalence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='attrition_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='patients',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
