# Generated by Django 2.1.7 on 2020-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20201027_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='attrition_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=3),
        ),
    ]
