# Generated by Django 3.1.3 on 2020-11-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20201121_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='attrition_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Medication'), ('2', 'Medical Equipment'), ('3', 'Medical Consumables'), ('4', 'Lab Equipment'), ('5', 'Lab Consumables')], max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='frequency',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='num_patients',
            field=models.FloatField(default=1, verbose_name='Number of Patients'),
        ),
    ]
