# Generated by Django 2.1.7 on 2020-10-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20201028_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='medicine_name',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
