# Generated by Django 3.1.3 on 2020-12-01 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20201121_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('supply_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msf_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='MSF Code')),
                ('supply_name', models.CharField(max_length=10000, null=True, verbose_name='Description')),
                ('frequency', models.FloatField(default=1)),
                ('attrition_rate', models.FloatField(default=0)),
                ('min_dosage', models.FloatField(blank=True, null=True)),
                ('max_dosage', models.FloatField(blank=True, null=True)),
                ('num_patients', models.FloatField(default=1, verbose_name='Number of Patients')),
                ('essential_item', models.BooleanField(blank=True, null=True, verbose_name='Essential NCD Item')),
                ('category', models.CharField(blank=True, choices=[('1', 'Medication'), ('2', 'Medical Equipment'), ('3', 'Medical Consumables'), ('4', 'Lab Equipment'), ('5', 'Lab Consumables')], max_length=10000, null=True)),
                ('comments', models.CharField(blank=True, max_length=10000)),
                ('unit', models.CharField(blank=True, choices=[('1', 'mg'), ('2', 'tab')], max_length=5)),
                ('disease_supplye', models.ManyToManyField(to='calc.Disease', verbose_name='Condition')),
            ],
            options={
                'verbose_name_plural': 'Supplies',
            },
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
