# Generated by Django 3.1.2 on 2020-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_pharmacy_medicine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='attrition_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dosage',
            field=models.FloatField(),
        ),
    ]
