# Generated by Django 3.1.3 on 2020-12-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20201201_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='disease_supplye',
            new_name='disease_supply',
        ),
    ]
