# Generated by Django 3.1.3 on 2020-12-08 19:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20201201_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentLine',
            fields=[
                ('tline_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tline_name', models.CharField(max_length=10000, null=True, verbose_name='Treatment Line Name')),
                ('tline_disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calc.disease', verbose_name='Conditio')),
                ('tline_supply', models.ManyToManyField(to='calc.Supply', verbose_name='Supply')),
            ],
        ),
    ]
