# Generated by Django 3.1.3 on 2020-12-08 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_treatmentline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentline',
            name='tline_disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calc.disease', verbose_name='Condition'),
        ),
    ]
