# Generated by Django 2.1.7 on 2020-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20201102_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='dosage',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='three_mth_consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
