# Generated by Django 2.1.7 on 2020-11-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20201111_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='flag',
        ),
    ]
