# Generated by Django 3.1.3 on 2020-12-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20201209_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='attrition_rate',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='num_patients',
        ),
        migrations.AlterField(
            model_name='supply',
            name='unit',
            field=models.CharField(blank=True, choices=[('mg', 'mg'), ('tab', 'tab'), ('ampules', 'ampules'), ('vial', 'vial'), ('ml', 'ml')], max_length=7),
        ),
    ]
