# Generated by Django 3.1.3 on 2021-02-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_auto_20210222_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='daily_dose',
        ),
        migrations.AddField(
            model_name='supply',
            name='daily_recommended_dose',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_frequency',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', '1 x day'), ('2', '2 x day'), (3, '3 x day'), (4, '4 x day'), (5, '5 x day')], max_length=10, null=True),
        ),
    ]
