# Generated by Django 3.1.3 on 2021-03-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_auto_20210329_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='supply_strength',
        ),
        migrations.AlterField(
            model_name='supply',
            name='packaging_presentation',
            field=models.CharField(blank=True, choices=[('1', 'tablet'), ('2', 'ampule'), ('3', 'vial'), ('4', 'bottle')], max_length=10),
        ),
        migrations.AlterField(
            model_name='supply',
            name='packaging_size',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Packaging'),
        ),
    ]
